name: test

on:
  workflow_call:
    inputs:
      application_name:
        required: true
        type: string
      aws_ebs_application_name:
        required: true
        type: string
      aws_ebs_environment_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      branch:
        required: true
        type: string
      build_type:
        required: true
        type: choice
        options:
          - war
          - zip
      commit_sha:
        required: true
        type: string
      github_repository:
        required: true
        type: string
      s3_bucket_name:
        required: true
        type: string

jobs:
  print_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checking-out current branch
        uses: actions/checkout@v3
        with:
          repository: '${{ inputs.github_repository }}'
          ref: '${{ inputs.branch }}'
      - name: Configuring ENV
        run: |
          branch_normailized=${{ inputs.branch }}
          branch_normailized=${branch_normailized#refs/heads/}
          branch_normailized=${branch_normailized//[^[:alnum:]]/-}
          s3_build_directory=s3://${{ inputs.s3_bucket_name }}/${{ inputs.application_name }}/$branch_normailized/
          target_build=ref-${{ inputs.commit_sha }}.${{ inputs.build_type }}
          s3_build_key=${{ inputs.application_name }}/$branch_normailized/$target_build
          version_label=ver-${{ inputs.commit_sha }}

          echo "AWS_EBS_APPLICATION_NAME=${{ inputs.aws_ebs_application_name }}" >> $GITHUB_ENV
          echo "AWS_EBS_ENVIRONMENT_NAME=${{ inputs.aws_ebs_environment_name }}" >> $GITHUB_ENV
          echo "AWS_PAGER=''" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME=${{ inputs.s3_bucket_name }}" >> $GITHUB_ENV
          echo "S3_BUILD_KEY=$s3_build_key" >> $GITHUB_ENV
          echo "S3_BUILD_DIRECTORY=$s3_build_directory" >> $GITHUB_ENV
          echo "TARGET_BUILD=$target_build" >> $GITHUB_ENV
          echo "VERSION_LABEL=$version_label" >> $GITHUB_ENV
          echo $GITHUB_ENV
      # # - name: Installing required system-level dependencies
      # #   run: |
      # #     curl -s https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o ~/awscliv2.zip
      # #     unzip -q ~/awscliv2.zip -d ~/
      # #     sudo ~/aws/install
      # #     sudo apt-get -qq install software-properties-common
      # #     sudo apt-add-repository universe -y
      # #     sudo apt-get -qq update
      # #     sudo apt-get -qq install maven -y
      # - name: Configuring AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: $AWS_REGION
      # - name: Setting-up JDK
      #   if: ${{ inputs.build_type == 'war' }}
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: temurin
      #     java-version: 8
      # - name: Building
      #   run: ./.github/scripts/build/${{ inputs.build_type }}.sh
      # - name: Deploying
      #   run: ./.github/scripts/deploy.sh
